# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: sglang-disagg-multinode
spec:
  backendFramework: sglang
  components:
  - name: Frontend
    podTemplate:
      spec:
        containers:
        - image: my-registry/sglang-runtime:my-tag
          name: main
    replicas: 1
    type: frontend
  - multinode:
      nodeCount: 2
    name: decode
    podTemplate:
      spec:
        containers:
        - args:
          - --model-path
          - Qwen/Qwen3-0.6B
          - --served-model-name
          - Qwen/Qwen3-0.6B
          - --tp-size
          - "8"
          - --trust-remote-code
          - --disaggregation-mode
          - decode
          - --disaggregation-transfer-backend
          - nixl
          - --disaggregation-bootstrap-port
          - "30001"
          - --host
          - 0.0.0.0
          - --mem-fraction-static
          - "0.82"
          command:
          - python3
          - -m
          - dynamo.sglang
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: my-registry/sglang-runtime:my-tag
          name: main
          resources:
            limits:
              nvidia.com/gpu: "4"
          workingDir: /workspace/examples/backends/sglang
    replicas: 1
    type: decode
  - multinode:
      nodeCount: 2
    name: prefill
    podTemplate:
      spec:
        containers:
        - args:
          - --model-path
          - Qwen/Qwen3-0.6B
          - --served-model-name
          - Qwen/Qwen3-0.6B
          - --tp-size
          - "8"
          - --trust-remote-code
          - --disaggregation-mode
          - prefill
          - --disaggregation-transfer-backend
          - nixl
          - --disaggregation-bootstrap-port
          - "30001"
          - --mem-fraction-static
          - "0.82"
          - --host
          - 0.0.0.0
          command:
          - python3
          - -m
          - dynamo.sglang
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: my-registry/sglang-runtime:my-tag
          name: main
          resources:
            limits:
              nvidia.com/gpu: "4"
          workingDir: /workspace/examples/backends/sglang
    replicas: 1
    type: prefill
  env:
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        key: HF_TOKEN
        name: hf-token-secret
  - name: GLOO_SOCKET_IFNAME
    value: eth0
