# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: planner-profile-data
data:
  prefill_raw_data.json: |
    {
      "prefill_isl":          [128, 256, 512, 1024, 2048],
      "prefill_ttft":         [12,  18,  30,  55,   105],
      "prefill_thpt_per_gpu": [9800, 8500, 6200, 3800, 2000]
    }
  decode_raw_data.json: |
    {
      "x_kv_usage":       [0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.3, 0.5, 0.5, 0.5, 0.5, 0.7, 0.7, 0.7, 0.7, 0.9, 0.9, 0.9, 0.9],
      "y_context_length": [128, 512, 1024, 2048, 128, 512, 1024, 2048, 128, 512, 1024, 2048, 128, 512, 1024, 2048, 128, 512, 1024, 2048],
      "z_itl":            [5, 6, 7, 9, 6, 7, 8, 10, 7, 8, 10, 12, 8, 10, 12, 15, 10, 12, 15, 20],
      "z_thpt_per_gpu":   [4500, 4000, 3500, 2800, 4200, 3700, 3200, 2500, 3800, 3300, 2800, 2200, 3400, 2900, 2400, 1800, 2800, 2400, 1900, 1400],
      "max_kv_tokens": 32768
    }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-template
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            deviceClassName: gpu.intel.com
            count: 1
---
apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg-planner-xpu
spec:
  components:
  - name: Frontend
    podTemplate:
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          name: main
    replicas: 1
    type: frontend
  - name: Planner
    podTemplate:
      spec:
        containers:
        - args:
          - --config
          - '{"environment": "kubernetes", "backend": "vllm", "throughput_adjustment_interval_seconds":
            60, "prefill_engine_num_gpu": 1, "decode_engine_num_gpu": 1, "profile_results_dir":
            "/workspace/profiling_results"}'
          command:
          - python3
          - -m
          - dynamo.planner
          image: nvcr.io/nvidia/ai-dynamo/dynamo-planner:my-tag
          name: main
          volumeMounts:
          - mountPath: /workspace/profiling_results
            name: planner-profile-data
            readOnly: true
        volumes:
        - configMap:
            name: planner-profile-data
          name: planner-profile-data
    replicas: 1
    type: planner
  - name: decode
    podTemplate:
      spec:
        containers:
        - args:
          - --model
          - Qwen/Qwen3-0.6B
          - --disaggregation-mode
          - decode
          - --kv-transfer-config
          - '{"kv_connector":"NixlConnector","kv_role":"kv_consumer","kv_buffer_device":"xpu"}'
          - --block-size
          - "64"
          command:
          - python3
          - -m
          - dynamo.vllm
          env:
          - name: VLLM_TARGET_DEVICE
            value: xpu
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime-xpu:my-tag
          name: main
          resources:
            claims:
            - name: gpu
            requests:
              ephemeral-storage: 2Gi
          workingDir: /workspace/examples/backends/vllm
        resourceClaims:
        - name: gpu
          resourceClaimTemplateName: gpu-template
    replicas: 1
    type: decode
  - name: prefill
    podTemplate:
      spec:
        containers:
        - args:
          - --model
          - Qwen/Qwen3-0.6B
          - --disaggregation-mode
          - prefill
          - --kv-transfer-config
          - '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_buffer_device":"xpu"}'
          - --block-size
          - "64"
          command:
          - python3
          - -m
          - dynamo.vllm
          env:
          - name: VLLM_TARGET_DEVICE
            value: xpu
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime-xpu:my-tag
          name: main
          resources:
            claims:
            - name: gpu
            requests:
              ephemeral-storage: 2Gi
          workingDir: /workspace/examples/backends/vllm
        resourceClaims:
        - name: gpu
          resourceClaimTemplateName: gpu-template
    replicas: 1
    type: prefill
