# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-agg-router
spec:
  components:
  - name: Frontend
    podTemplate:
      spec:
        containers:
        - env:
          - name: DYN_ROUTER_MODE
            value: kv
          image: my-registry/tensorrtllm-runtime:my-tag
          name: main
    replicas: 1
    type: frontend
  - name: TRTLLMWorker
    podTemplate:
      spec:
        containers:
        - args:
          - --model-path
          - Qwen/Qwen3-0.6B
          - --served-model-name
          - Qwen/Qwen3-0.6B
          - --extra-engine-args
          - ./examples/backends/trtllm/engine_configs/qwen3/agg.yaml
          - --publish-kv-events
          command:
          - python3
          - -m
          - dynamo.trtllm
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: my-registry/tensorrtllm-runtime:my-tag
          name: main
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              # Increase this value for larger models.
              ephemeral-storage: 2Gi
          workingDir: /workspace/
    replicas: 2
    type: worker
