# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: qwen
spec:
  backendFramework: vllm
  components:
  - name: Epp
    type: epp
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: main
          env:
          - name: DYN_KV_CACHE_BLOCK_SIZE
            value: "128"
          - name: DYN_MODEL_NAME
            value: Qwen/Qwen3-0.6B
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:my-tag
  - name: worker
    type: decode
    replicas: 1
    sharedMemorySize: 2Gi
    frontendSidecar: sidecar-frontend
    podTemplate:
      spec:
        containers:
        - name: main
          args:
          - python3 -m dynamo.vllm --model $MODEL_PATH --served-model-name $SERVED_MODEL_NAME
            --tensor-parallel-size 1 --data-parallel-size 1 --gpu-memory-utilization
            0.90 --enable-prefix-caching --block-size 128 --kv-events-config '{"enable_kv_cache_events":true}'
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: Qwen/Qwen3-0.6B
          - name: MODEL_PATH
            value: Qwen/Qwen3-0.6B
          - name: DYN_STORE_KV
            value: mem
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          workingDir: /workspace/examples/backends/vllm
        - name: sidecar-frontend
          args:
          - -m
          - dynamo.frontend
          - --router-mode
          - direct
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:my-tag
