#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate, render, and compose Kustomize recipe variants."""

from __future__ import annotations

import argparse
import itertools
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, TypeAlias

import yaml

if TYPE_CHECKING:
    from jinja2.sandbox import ImmutableSandboxedEnvironment

SPDX_HEADER = (
    "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0"
)
REPO_ROOT = Path(__file__).resolve().parents[1]
OPENAPI_GENERATOR = REPO_ROOT / "scripts/generate_kustomize_openapi.py"
KUSTOMIZATION_FILE = "kustomization.yaml"
TEMPLATE_KUSTOMIZATION_FILE = "kustomization.yaml.j2"
TEMPLATE_VALUES_FILE = "values.yaml"
TEMPLATE_COMPONENTS_DIR = "components"
LEGACY_TEMPLATE_COMPONENTS_DIR = "generated-components"
GENERATED_OVERLAY_PREFIX = "# Regenerate: scripts/kustomize-matrix.py unfold "
GENERATED_TEMPLATE_PREFIX = "# Template source: "
GENERATED_MANIFEST_PREFIX = "#   scripts/kustomize-matrix.py render "
LEGACY_GENERATED_OVERLAY_PREFIX = "# Generated by: scripts/kustomize-matrix.py unfold "
LEGACY_GENERATED_MANIFEST_PREFIX = (
    "# To update the checked-in recipe: scripts/kustomize-matrix.py render "
)
LEGACY_MATRIX_RENDER_COMMAND_PREFIX = (
    "# Regenerate: scripts/kustomize-matrix.py render "
)
PathPart: TypeAlias = str | int
YamlPath: TypeAlias = tuple[PathPart, ...]
FIRST_TOP_LEVEL_KEYS = ("apiVersion", "kind", "metadata")
NAME_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*\Z")
TEMPLATE_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
GENERATED_SOURCE_COMMENT_PREFIXES = (
    "# Generated file.",
    "# Regenerate this matrix's public overlays",
    GENERATED_OVERLAY_PREFIX,
    GENERATED_TEMPLATE_PREFIX,
)


@dataclass(frozen=True)
class TemplateSelection:
    source: Path
    output_path: Path


@dataclass(frozen=True)
class TemplateBundle:
    selection: TemplateSelection
    sources: tuple[Path, ...]
    files: dict[Path, Path]


@dataclass(frozen=True)
class MatrixValue:
    name: str
    components: tuple[Path, ...]
    templates: tuple[TemplateSelection, ...]
    values: dict[str, Any]
    sort_options: str | None = None


DEFAULT_SORT_OPTIONS = "sortOptions:\n  order: fifo"


@dataclass(frozen=True)
class MatrixVariant:
    name: str
    components: tuple[Path, ...]
    templates: tuple[TemplateSelection, ...]
    values: dict[str, Any]
    # Rendered `sortOptions:` block for this variant's generated overlay.
    # Kustomize reads sortOptions from the kustomization it builds, so a base
    # cannot set them -- only the generated overlay can. Per variant, not per
    # matrix: only the variant that needs an order pays for one.
    sort_options: str = DEFAULT_SORT_OPTIONS


@dataclass(frozen=True)
class MatrixConfig:
    path: Path
    source: Path
    name_template: str
    dimensions: tuple[tuple[str, tuple[MatrixValue, ...]], ...]

    @property
    def recipe_root(self) -> Path:
        return self.path.parent

    @property
    def overlays_dir(self) -> Path:
        return self.recipe_root / "kustomize/overlays"

    @property
    def command_path(self) -> str:
        return display_path(self.path)


@dataclass(frozen=True)
class DocumentId:
    api_version: str
    kind: str
    name: str


@dataclass
class CommentBlock:
    doc_id: DocumentId
    path: YamlPath
    lines: list[str]


@dataclass
class DocumentScan:
    doc_id: DocumentId | None
    comments: list[CommentBlock]
    targets: dict[YamlPath, int]


@dataclass
class TopLevelBlock:
    key: str | None
    lines: list[str]


class ResourceCollection(dict[str, dict[str, Any]]):
    def __init__(self, kind: str) -> None:
        super().__init__()
        self.kind = kind


def display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def kustomize_command() -> list[str]:
    if shutil.which("kustomize"):
        return ["kustomize", "build"]
    if shutil.which("kubectl"):
        return ["kubectl", "kustomize"]
    raise RuntimeError("install kustomize or kubectl to build a Kustomization")


def load_yaml_mapping(path: Path) -> dict[str, Any]:
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"invalid YAML in {display_path(path)}: {exc}") from exc
    if not isinstance(value, dict):
        raise TypeError(f"expected a YAML mapping in {display_path(path)}")
    return value


def require_string(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{context} must be a non-empty string")
    return value


def resolve_component_paths(
    values: Any, matrix_path: Path, context: str
) -> tuple[Path, ...]:
    if not isinstance(values, list) or not all(
        isinstance(value, str) for value in values
    ):
        raise ValueError(f"{context} must be a list of component paths")

    components = tuple((matrix_path.parent / value).resolve() for value in values)
    for component in components:
        if not component.is_dir():
            raise ValueError(
                f"Kustomize Component is not a directory: {display_path(component)}"
            )
    return components


def resolve_template_selections(
    values: Any, matrix_path: Path, context: str
) -> tuple[TemplateSelection, ...]:
    if not isinstance(values, list):
        raise ValueError(f"{context} must be a list of template mappings")

    templates: list[TemplateSelection] = []
    for index, value in enumerate(values):
        item_context = f"{context}[{index}]"
        if not isinstance(value, dict) or set(value) != {"source", "path"}:
            raise ValueError(f"{item_context} must contain exactly source and path")
        source_value = require_string(value.get("source"), f"{item_context}.source")
        output_value = require_string(value.get("path"), f"{item_context}.path")
        output_path = Path(output_value)
        if (
            output_path.is_absolute()
            or output_path == Path(".")
            or len(output_path.parts) < 2
            or output_path.parts[0] != TEMPLATE_COMPONENTS_DIR
            or any(part in {".", ".."} for part in output_path.parts)
        ):
            raise ValueError(
                f"{item_context}.path must be a relative path under "
                f"{TEMPLATE_COMPONENTS_DIR}/: {output_value!r}"
            )
        source = (matrix_path.parent / source_value).resolve()
        if not source.is_dir():
            raise ValueError(
                f"Kustomize template is not a directory: {display_path(source)}"
            )
        selection = TemplateSelection(source=source, output_path=output_path)
        resolve_template_bundle(selection)
        templates.append(selection)
    return tuple(templates)


def load_variant_values(value: Any, context: str) -> dict[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict) or not all(
        isinstance(key, str) and key for key in value
    ):
        raise ValueError(f"{context} must be a mapping with non-empty string keys")
    return value


def load_matrix(path: str) -> MatrixConfig:
    matrix_path = Path(path).resolve()
    if not matrix_path.is_file():
        raise ValueError(f"matrix file does not exist: {path}")

    data = load_yaml_mapping(matrix_path)
    unknown_keys = set(data) - {"source", "nameTemplate", "matrix"}
    if unknown_keys:
        raise ValueError(
            f"unsupported matrix key in {display_path(matrix_path)}: {min(unknown_keys)}"
        )

    source_value = require_string(data.get("source"), "source")
    source = (matrix_path.parent / source_value).resolve()
    if not source.is_dir():
        raise ValueError(f"Kustomize source is not a directory: {source_value}")

    name_template = require_string(data.get("nameTemplate"), "nameTemplate")
    raw_matrix = data.get("matrix")
    if not isinstance(raw_matrix, dict) or not raw_matrix:
        raise ValueError("matrix must be a non-empty mapping of dimensions")

    dimensions: list[tuple[str, tuple[MatrixValue, ...]]] = []
    for dimension, raw_values in raw_matrix.items():
        if not isinstance(dimension, str) or not TEMPLATE_PATTERN.fullmatch(
            f"${{{dimension}}}"
        ):
            raise ValueError(f"invalid matrix dimension name: {dimension!r}")
        if not isinstance(raw_values, list) or not raw_values:
            raise ValueError(
                f"matrix dimension {dimension!r} must contain at least one value"
            )

        values: list[MatrixValue] = []
        value_names: set[str] = set()
        for index, raw_value in enumerate(raw_values):
            context = f"matrix.{dimension}[{index}]"
            if not isinstance(raw_value, dict):
                raise TypeError(f"{context} must be a mapping")
            unknown_value_keys = set(raw_value) - {
                "name",
                "components",
                "templates",
                "values",
                "sortOptions",
            }
            if unknown_value_keys:
                raise ValueError(
                    f"unsupported key in {context}: {min(unknown_value_keys)}"
                )
            name = require_string(raw_value.get("name"), f"{context}.name")
            if not NAME_PATTERN.fullmatch(name):
                raise ValueError(
                    f"{context}.name is not a valid variant name: {name!r}"
                )
            if name in value_names:
                raise ValueError(
                    f"matrix dimension {dimension!r} repeats value {name!r}"
                )
            value_names.add(name)
            values.append(
                MatrixValue(
                    name=name,
                    components=resolve_component_paths(
                        raw_value.get("components", []),
                        matrix_path,
                        f"{context}.components",
                    ),
                    templates=resolve_template_selections(
                        raw_value.get("templates", []),
                        matrix_path,
                        f"{context}.templates",
                    ),
                    values=load_variant_values(
                        raw_value.get("values"), f"{context}.values"
                    ),
                    sort_options=(
                        parse_sort_options(raw_value["sortOptions"])
                        if "sortOptions" in raw_value
                        else None
                    ),
                )
            )
        dimensions.append((dimension, tuple(values)))

    template_dimensions = set(TEMPLATE_PATTERN.findall(name_template))
    unknown_template_dimensions = template_dimensions - {name for name, _ in dimensions}
    if unknown_template_dimensions:
        raise ValueError(
            "nameTemplate references unknown dimension: "
            f"{min(unknown_template_dimensions)}"
        )
    if not template_dimensions:
        raise ValueError("nameTemplate must reference at least one matrix dimension")

    return MatrixConfig(
        path=matrix_path,
        source=source,
        name_template=name_template,
        dimensions=tuple(dimensions),
    )


def expand_matrix(config: MatrixConfig) -> list[MatrixVariant]:
    variants: list[MatrixVariant] = []
    names: set[str] = set()
    value_lists = [values for _, values in config.dimensions]
    dimension_names = [name for name, _ in config.dimensions]

    for values in itertools.product(*value_lists):
        replacements = dict(
            zip(dimension_names, (value.name for value in values), strict=True)
        )
        name = TEMPLATE_PATTERN.sub(
            lambda match, replacements=replacements: replacements[match.group(1)],
            config.name_template,
        )
        if not NAME_PATTERN.fullmatch(name):
            raise ValueError(
                f"nameTemplate generated an invalid variant name: {name!r}"
            )
        if name in names:
            raise ValueError(
                f"nameTemplate generated duplicate variant name {name!r}; include every varying dimension"
            )
        names.add(name)

        components = tuple(
            component for value in values for component in value.components
        )
        if len(set(components)) != len(components):
            raise ValueError(
                f"variant {name!r} selects the same Component more than once"
            )
        templates = tuple(template for value in values for template in value.templates)
        if len({template.source for template in templates}) != len(templates):
            raise ValueError(
                f"variant {name!r} selects the same template more than once"
            )
        output_paths = tuple(template.output_path for template in templates)
        if len(set(output_paths)) != len(output_paths):
            raise ValueError(
                f"variant {name!r} assigns the same local Component path more than once"
            )
        for first, second in itertools.combinations(output_paths, 2):
            if first in second.parents or second in first.parents:
                raise ValueError(
                    f"variant {name!r} assigns overlapping local Component paths: "
                    f"{first} and {second}"
                )
        variant_values: dict[str, Any] = {}
        for value in values:
            for key, template_value in value.values.items():
                if key in variant_values:
                    raise ValueError(
                        f"variant {name!r} defines value {key!r} more than once"
                    )
                variant_values[key] = template_value
        selected_sort_options = [
            value.sort_options for value in values if value.sort_options is not None
        ]
        if len(set(selected_sort_options)) > 1:
            raise ValueError(
                f"variant {name!r} selects conflicting sortOptions from more than "
                f"one dimension"
            )
        variants.append(
            MatrixVariant(
                name=name,
                components=components,
                templates=templates,
                values=variant_values,
                sort_options=(
                    selected_sort_options[0]
                    if selected_sort_options
                    else DEFAULT_SORT_OPTIONS
                ),
            )
        )

    return variants


def relative_path(path: Path, root: Path) -> str:
    return os.path.relpath(path, root)


def overlay_path(config: MatrixConfig, variant: MatrixVariant) -> Path:
    return config.overlays_dir / variant.name


def generated_template_component_path(
    config: MatrixConfig, variant: MatrixVariant, template: TemplateSelection
) -> Path:
    return overlay_path(config, variant) / template.output_path


def build_base_resource_index(source: Path) -> dict[str, ResourceCollection]:
    result = subprocess.run(
        [*kustomize_command(), str(source)],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())

    try:
        documents = list(yaml.safe_load_all(result.stdout))
    except yaml.YAMLError as exc:
        raise ValueError(
            f"invalid Kustomize output for {display_path(source)}: {exc}"
        ) from exc

    index: dict[str, ResourceCollection] = {}
    for document in documents:
        if document is None:
            continue
        if not isinstance(document, dict):
            raise ValueError(
                f"Kustomize source {display_path(source)} produced a non-mapping resource"
            )
        kind = document.get("kind")
        metadata = document.get("metadata")
        name = metadata.get("name") if isinstance(metadata, dict) else None
        if not isinstance(kind, str) or not kind:
            raise ValueError(
                f"Kustomize source {display_path(source)} produced a resource without kind"
            )
        if not isinstance(name, str) or not name:
            raise ValueError(
                f"Kustomize source {display_path(source)} produced {kind} without metadata.name"
            )
        collection = index.setdefault(kind.lower(), ResourceCollection(kind))
        if name in collection:
            raise ValueError(
                f"Kustomize source {display_path(source)} produces duplicate "
                f"{kind}/{name} resources"
            )
        collection[name] = document
    return index


def template_source_files(source: Path) -> dict[Path, Path]:
    files: dict[Path, Path] = {}
    for source_path in sorted(source.iterdir()):
        if not source_path.is_file() or source_path.name == TEMPLATE_VALUES_FILE:
            continue
        if not source_path.name.endswith((".yaml", ".yaml.j2")):
            continue
        output_name = (
            source_path.name.removesuffix(".j2")
            if source_path.name.endswith(".yaml.j2")
            else source_path.name
        )
        output_path = Path(output_name)
        if output_path in files:
            raise ValueError(
                f"Kustomize template {display_path(source)} contains multiple sources for "
                f"{output_name}"
            )
        files[output_path] = source_path
    return files


def resolve_template_bundle(template: TemplateSelection) -> TemplateBundle:
    sources = (template.source.parent, template.source)
    files: dict[Path, Path] = {}
    for source in sources:
        files.update(template_source_files(source))
    if Path(KUSTOMIZATION_FILE) not in files:
        raise ValueError(
            "Kustomize template and its parent must provide kustomization.yaml or "
            f"{TEMPLATE_KUSTOMIZATION_FILE}: {display_path(template.source)}"
        )
    return TemplateBundle(selection=template, sources=sources, files=files)


def template_values(template: TemplateBundle) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    for source in template.sources:
        values_path = source / TEMPLATE_VALUES_FILE
        if not values_path.exists():
            continue
        merged.update(
            load_variant_values(
                load_yaml_mapping(values_path), display_path(values_path)
            )
        )
    return merged


def merged_template_values(
    templates: tuple[TemplateBundle, ...], overrides: dict[str, Any]
) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    value_sources: dict[str, TemplateBundle] = {}
    for template in templates:
        for key, value in template_values(template).items():
            if key in merged:
                raise ValueError(
                    "templates "
                    f"{display_path(value_sources[key].selection.source)} and "
                    f"{display_path(template.selection.source)} both define value {key!r}"
                )
            merged[key] = value
            value_sources[key] = template
    merged.update(overrides)
    return merged


def only(resources: ResourceCollection) -> dict[str, Any]:
    if not isinstance(resources, ResourceCollection):
        raise ValueError("only requires a Base resource kind index")
    if len(resources) == 1:
        return next(iter(resources.values()))
    names = ", ".join(sorted(resources)) or "none"
    raise ValueError(
        f"expected exactly one {resources.kind} resource, found {len(resources)}: {names}"
    )


def template_environment() -> ImmutableSandboxedEnvironment:
    try:
        from jinja2 import StrictUndefined
        from jinja2.sandbox import ImmutableSandboxedEnvironment
    except ImportError as exc:
        raise RuntimeError(
            "Jinja2 is required to render Kustomize templates; install jinja2==3.1.6"
        ) from exc

    environment = ImmutableSandboxedEnvironment(
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    environment.filters["only"] = only
    return environment


def render_jinja_template(
    source_path: Path,
    base: dict[str, ResourceCollection],
    values: dict[str, Any],
) -> str:
    try:
        return (
            template_environment()
            .from_string(source_path.read_text(encoding="utf-8"))
            .render(base=base, values=values)
        )
    except Exception as exc:
        raise ValueError(
            f"failed to render template source {display_path(source_path)}: {exc}"
        ) from exc


def render_template_assets(
    template: TemplateBundle,
    component_dir: Path,
    base: dict[str, ResourceCollection],
    values: dict[str, Any],
) -> dict[Path, str]:
    assets: dict[Path, str] = {}
    for relative_output, source_path in sorted(template.files.items()):
        if relative_output == Path(KUSTOMIZATION_FILE):
            continue
        output_path = component_dir / relative_output
        if output_path in assets:
            raise ValueError(
                f"template {display_path(template.selection.source)} produces duplicate asset "
                f"{relative_output}"
            )
        if source_path.suffix == ".j2":
            content = render_jinja_template(source_path, base, values)
        else:
            content = source_path.read_text(encoding="utf-8")
        assets[output_path] = content
    return assets


def bundle_contains_path(
    template: TemplateBundle, relative_source: Path, reference: str
) -> bool:
    path = Path(os.path.normpath(relative_source.parent / reference))
    if path.is_absolute() or path == Path("..") or ".." in path.parts:
        return False
    return any(
        relative_path == path or relative_path.is_relative_to(path)
        for relative_path in template.files
    )


def external_path_replacements(
    component: dict[str, Any],
    template: TemplateBundle,
    source_path: Path,
    relative_source: Path,
    component_dir: Path,
) -> dict[str, str]:
    replacements: dict[str, str] = {}
    for key in ("bases", "components", "resources"):
        references = component.get(key)
        if not isinstance(references, list):
            continue
        for reference in references:
            if not isinstance(reference, str) or "://" in reference:
                continue
            if bundle_contains_path(template, relative_source, reference):
                continue
            source = (source_path.parent / reference).resolve()
            if not source.exists():
                continue
            replacements[reference] = relative_path(source, component_dir)
    return replacements


def rebase_rendered_paths(
    rendered: str, replacements: dict[str, str], source_path: Path
) -> str:
    for source, replacement in replacements.items():
        pattern = re.compile(
            rf"^(?P<prefix>\s*-\s*)(?P<quote>[\"']?)"
            rf"{re.escape(source)}(?P=quote)(?P<suffix>\s*(?:#.*)?)$",
            re.MULTILINE,
        )
        rendered, count = pattern.subn(
            rf"\g<prefix>\g<quote>{replacement}\g<quote>\g<suffix>", rendered
        )
        if count == 0:
            raise ValueError(
                f"failed to rebase path {source!r} in {display_path(source_path)}"
            )
    return rendered


def render_template_component(
    template: TemplateBundle,
    base: dict[str, ResourceCollection],
    values: dict[str, Any],
    component_dir: Path | None = None,
) -> str:
    source_path = template.files[Path(KUSTOMIZATION_FILE)]
    rendered = (
        render_jinja_template(source_path, base, values)
        if source_path.suffix == ".j2"
        else source_path.read_text(encoding="utf-8")
    )

    try:
        documents = list(yaml.safe_load_all(rendered))
    except yaml.YAMLError as exc:
        raise ValueError(
            f"template {display_path(template.selection.source)} rendered invalid YAML: {exc}"
        ) from exc
    if len(documents) != 1 or not isinstance(documents[0], dict):
        raise ValueError(
            f"template {display_path(template.selection.source)} must render one Kustomize Component mapping"
        )
    component = documents[0]
    if (
        component.get("apiVersion") != "kustomize.config.k8s.io/v1alpha1"
        or component.get("kind") != "Component"
    ):
        raise ValueError(
            f"template {display_path(template.selection.source)} must render a v1alpha1 Kustomize Component"
        )
    if component_dir:
        rendered = rebase_rendered_paths(
            rendered,
            external_path_replacements(
                component,
                template,
                source_path,
                Path(KUSTOMIZATION_FILE),
                component_dir,
            ),
            source_path,
        )
    return rendered.rstrip() + "\n"


def remove_leading_spdx_header(content: str) -> str:
    lines = content.splitlines(keepends=True)
    while lines and lines[0].startswith("# SPDX-"):
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    return "".join(lines)


def generated_template_file(
    config: MatrixConfig, template: TemplateSelection, rendered: str
) -> str:
    return generated_template_content(
        config,
        f"{GENERATED_TEMPLATE_PREFIX}{display_path(template.source)}",
        rendered,
    )


def generated_template_content(
    config: MatrixConfig, source_comment: str, rendered: str
) -> str:
    return "\n".join(
        [
            SPDX_HEADER,
            "",
            "# Generated file. For repository contributors, do not edit this checked-in copy.",
            "# Regenerate this matrix's public overlays and template Components from the repository root:",
            f"{GENERATED_OVERLAY_PREFIX}{config.command_path}",
            source_comment,
            "",
            remove_leading_spdx_header(rendered).rstrip(),
            "",
        ]
    )


def parse_sort_options(raw: Any) -> str:
    """Render an optional matrix `sortOptions` mapping into a kustomization block.

    Omitted (the normal case) keeps the repository-wide `order: fifo`, so matrices
    that do not declare it render byte-identically.
    """
    if raw is None:
        return DEFAULT_SORT_OPTIONS
    if not isinstance(raw, dict) or not raw:
        raise ValueError("sortOptions must be a non-empty mapping")
    unknown = set(raw) - {"order", "legacySortOptions"}
    if unknown:
        raise ValueError(f"unsupported sortOptions key: {min(unknown)}")
    order = require_string(raw.get("order"), "sortOptions.order")
    if order not in {"fifo", "legacy"}:
        raise ValueError(f"sortOptions.order must be fifo or legacy, got {order!r}")

    lines = ["sortOptions:", f"  order: {order}"]
    legacy = raw.get("legacySortOptions")
    if legacy is not None:
        if order != "legacy":
            raise ValueError("sortOptions.legacySortOptions requires order: legacy")
        if not isinstance(legacy, dict):
            raise ValueError("sortOptions.legacySortOptions must be a mapping")
        unknown_legacy = set(legacy) - {"orderFirst", "orderLast"}
        if unknown_legacy:
            raise ValueError(
                f"unsupported legacySortOptions key: {min(unknown_legacy)}"
            )
        legacy_lines: list[str] = []
        for key in ("orderFirst", "orderLast"):
            kinds = legacy.get(key)
            if kinds is None:
                continue
            if not isinstance(kinds, list) or not all(
                isinstance(kind, str) for kind in kinds
            ):
                raise ValueError(f"legacySortOptions.{key} must be a list of kinds")
            legacy_lines.append(f"    {key}: {json.dumps(kinds)}")
        # Emitting the key with no children renders `legacySortOptions:`, which
        # parses back as null rather than an empty mapping, and Kustomize then
        # applies its own hardcoded legacy ordering. Reject instead: omitting the
        # key entirely is the way to ask for the default ordering.
        if not legacy_lines:
            raise ValueError(
                "sortOptions.legacySortOptions must set orderFirst or orderLast; "
                "omit the key to keep Kustomize's default legacy ordering"
            )
        lines.append("  legacySortOptions:")
        lines.extend(legacy_lines)
    return "\n".join(lines)


def unfolded_kustomization(
    config: MatrixConfig, variant: MatrixVariant, template_components: tuple[Path, ...]
) -> str:
    overlay_dir = overlay_path(config, variant)
    lines = [
        SPDX_HEADER,
        "",
        "# Generated file. For repository contributors, do not edit this checked-in copy.",
        "# Regenerate this matrix's public overlays and template Components from the repository root:",
        f"{GENERATED_OVERLAY_PREFIX}{config.command_path}",
        "",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        *variant.sort_options.split("\n"),
        "resources:",
        f"  - {json.dumps(relative_path(config.source, overlay_dir))}",
    ]

    # A template can own a generic dependency whose patch order must precede variant additions.
    components = (*template_components, *variant.components)
    if components:
        lines.append("components:")
        lines.extend(
            f"  - {json.dumps(relative_path(component, overlay_dir))}"
            for component in components
        )
    return "\n".join(lines) + "\n"


def generated_overlay_paths(config: MatrixConfig) -> set[Path]:
    if not config.overlays_dir.exists():
        return set()
    generated: set[Path] = set()
    for path in config.overlays_dir.iterdir():
        kustomization = path / KUSTOMIZATION_FILE
        if not path.is_dir() or not kustomization.exists():
            continue
        content = kustomization.read_text(encoding="utf-8")
        if (
            GENERATED_OVERLAY_PREFIX in content
            or LEGACY_GENERATED_OVERLAY_PREFIX in content
        ):
            generated.add(path)
    return generated


def is_current_generated_overlay(config: MatrixConfig, path: Path) -> bool:
    marker = f"{GENERATED_OVERLAY_PREFIX}{config.command_path}"
    return marker in (path / KUSTOMIZATION_FILE).read_text(encoding="utf-8")


def generated_template_kustomizations(overlay_dir: Path) -> set[Path]:
    generated: set[Path] = set()
    for directory_name in (
        TEMPLATE_COMPONENTS_DIR,
        LEGACY_TEMPLATE_COMPONENTS_DIR,
    ):
        generated_dir = overlay_dir / directory_name
        if not generated_dir.is_dir():
            continue
        for kustomization in generated_dir.rglob(KUSTOMIZATION_FILE):
            if GENERATED_TEMPLATE_PREFIX in kustomization.read_text(encoding="utf-8"):
                generated.add(kustomization)
    return generated


def remove_generated_template_kustomization(kustomization: Path) -> None:
    component_dir = kustomization.parent
    shutil.rmtree(component_dir)
    for parent in component_dir.parents:
        try:
            parent.rmdir()
        except OSError:
            return
        if parent.name in (
            TEMPLATE_COMPONENTS_DIR,
            LEGACY_TEMPLATE_COMPONENTS_DIR,
        ):
            return


def generated_content_matches(path: Path, content: str) -> bool:
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8") == content


def write_generated_content(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def unfold_matrix(
    config: MatrixConfig, *, check: bool, clean: bool = False
) -> list[Path]:
    variants = expand_matrix(config)
    base = (
        build_base_resource_index(config.source)
        if any(variant.templates for variant in variants)
        else None
    )
    expected: dict[Path, str] = {}
    expected_template_kustomizations: set[Path] = set()
    expected_template_assets: dict[Path, set[Path]] = {}

    for variant in variants:
        template_components: list[Path] = []
        templates = tuple(
            resolve_template_bundle(template) for template in variant.templates
        )
        values = merged_template_values(templates, variant.values)
        for template in templates:
            selection = template.selection
            component_dir = generated_template_component_path(
                config, variant, selection
            )
            kustomization = component_dir / KUSTOMIZATION_FILE
            assert base is not None
            expected[kustomization] = generated_template_file(
                config,
                selection,
                render_template_component(template, base, values, component_dir),
            )
            assets = render_template_assets(template, component_dir, base, values)
            for path, content in assets.items():
                assets[path] = generated_template_file(config, selection, content)
            expected.update(assets)
            expected_template_kustomizations.add(kustomization)
            expected_template_assets[component_dir] = {
                kustomization,
                *assets,
            }
            template_components.append(component_dir)

        overlay_dir = overlay_path(config, variant)
        expected[overlay_dir / KUSTOMIZATION_FILE] = unfolded_kustomization(
            config, variant, tuple(template_components)
        )

    stale: list[Path] = []

    # Remove stale parents before writing expected descendants they would delete.
    expected_overlays = {overlay_path(config, variant) for variant in variants}
    generated_overlays = generated_overlay_paths(config)
    for path in sorted(generated_overlays):
        can_clean = clean or is_current_generated_overlay(config, path)
        kustomizations = generated_template_kustomizations(path)
        for kustomization in sorted(
            kustomizations,
            key=lambda item: (len(item.parts), str(item)),
            reverse=True,
        ):
            if kustomization in expected_template_kustomizations:
                continue
            stale.append(kustomization)
            if not check and can_clean:
                remove_generated_template_kustomization(kustomization)

    for path, content in expected.items():
        if not generated_content_matches(path, content):
            stale.append(path)
            if not check:
                write_generated_content(path, content)

    for component_dir, expected_paths in expected_template_assets.items():
        kustomization = component_dir / KUSTOMIZATION_FILE
        if not kustomization.exists():
            continue
        for source_path in component_dir.rglob("*"):
            if not source_path.is_file() or source_path in expected_paths:
                continue
            stale.append(source_path)
            if not check:
                source_path.unlink()

    for path in generated_overlays - expected_overlays:
        kustomization = path / KUSTOMIZATION_FILE
        stale.append(kustomization)
        if not check and (clean or is_current_generated_overlay(config, path)):
            kustomization.unlink()
            try:
                path.rmdir()
            except OSError:
                pass
    return stale


def generate_kustomize_openapi(*, check: bool) -> None:
    command = [sys.executable, str(OPENAPI_GENERATOR)]
    if check:
        command.append("--check")
    result = subprocess.run(
        command, cwd=REPO_ROOT, check=False, capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())


def starts_block_scalar(stripped_line: str) -> bool:
    if not stripped_line or stripped_line.startswith("#"):
        return False
    value = stripped_line.split("#", 1)[0].rstrip().rsplit(maxsplit=1)[-1]
    return value.startswith(("|", ">"))


def line_indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def parse_key_value(content: str) -> tuple[str, str] | None:
    if ":" not in content:
        return None
    key, value = content.split(":", 1)
    key = key.strip().strip("\"'")
    return (key, value.strip()) if key else None


def strip_inline_comment(value: str) -> str:
    return value.split("#", 1)[0].strip()


def scalar_value(value: str) -> str:
    return strip_inline_comment(value).strip("\"'")


def record_scalar(values: dict[YamlPath, str], path: YamlPath, value: str) -> None:
    value = scalar_value(value)
    if value:
        values[path] = value


def starts_nested_value(value: str, line: str) -> bool:
    stripped = strip_inline_comment(value)
    return not stripped or stripped.startswith(("&", "!")) or starts_block_scalar(line)


def scan_yaml(text: str) -> list[DocumentScan]:
    """Map YAML comments to fields without interpreting patch semantics."""

    docs: list[DocumentScan] = []
    comments: list[tuple[YamlPath, list[str]]] = []
    targets: dict[YamlPath, int] = {}
    values: dict[YamlPath, str] = {}
    stack: list[tuple[int, YamlPath]] = []
    sequence_indexes: dict[tuple[YamlPath, int], int] = {}
    pending_comments: list[str] = []
    block_scalar_indent: int | None = None

    def finish_document() -> None:
        nonlocal comments, targets, values, stack, sequence_indexes, pending_comments
        api_version = values.get(("apiVersion",))
        kind = values.get(("kind",))
        name = values.get(("metadata", "name"))
        doc_id = (
            DocumentId(api_version, kind, name)
            if api_version and kind and name
            else None
        )
        docs.append(
            DocumentScan(
                doc_id=doc_id,
                comments=[CommentBlock(doc_id, path, lines) for path, lines in comments]
                if doc_id
                else [],
                targets=targets,
            )
        )
        comments = []
        targets = {}
        values = {}
        stack = []
        sequence_indexes = {}
        pending_comments = []

    for line_number, line in enumerate(text.splitlines()):
        stripped = line.strip()
        indent = line_indent(line)
        if stripped == "---":
            finish_document()
            block_scalar_indent = None
            continue
        if block_scalar_indent is not None:
            if not stripped:
                continue
            if indent > block_scalar_indent:
                continue
            block_scalar_indent = None
        if starts_block_scalar(stripped):
            block_scalar_indent = indent
        if not stripped:
            continue
        if stripped.startswith("#"):
            if not stripped.startswith(("# SPDX-", *GENERATED_SOURCE_COMMENT_PREFIXES)):
                pending_comments.append(stripped)
            continue

        if stripped.startswith("- "):
            while stack and indent < stack[-1][0]:
                stack.pop()
            while (
                stack and indent == stack[-1][0] and isinstance(stack[-1][1][-1], int)
            ):
                stack.pop()
        else:
            while stack and indent <= stack[-1][0]:
                stack.pop()
        parent_path = stack[-1][1] if stack else ()
        line_paths: list[YamlPath] = []
        comment_path: YamlPath | None = None
        if stripped.startswith("- "):
            sequence_key = (parent_path, indent)
            item_index = sequence_indexes.get(sequence_key, 0)
            sequence_indexes[sequence_key] = item_index + 1
            item_path = (*parent_path, item_index)
            line_paths.append(item_path)
            content = stripped[2:].strip()
            parsed = parse_key_value(content)
            if parsed:
                key, value = parsed
                key_path = (*item_path, key)
                line_paths.append(key_path)
                record_scalar(values, key_path, value)
                if key == "name" and (name := scalar_value(value)):
                    comment_path = (*parent_path, f"name={name}")
                    line_paths.append(comment_path)
                if starts_nested_value(value, content):
                    stack.append((indent, key_path))
                else:
                    stack.append((indent, item_path))
            else:
                stack.append((indent, item_path))
        else:
            parsed = parse_key_value(stripped)
            if not parsed:
                continue
            key, value = parsed
            key_path = (*parent_path, key)
            line_paths.append(key_path)
            record_scalar(values, key_path, value)
            if starts_nested_value(value, stripped):
                stack.append((indent, key_path))
        for item_path in line_paths:
            targets.setdefault(item_path, line_number)
        if pending_comments and line_paths:
            comments.append((comment_path or line_paths[0], pending_comments))
            pending_comments = []
    finish_document()
    return docs


def source_comment_paths(kustomization_dir: Path) -> list[Path]:
    """Find YAML sources from resources and Components, including nested parents."""

    source_paths: set[Path] = set()
    visited: set[Path] = set()

    def visit(directory: Path) -> None:
        directory = directory.resolve()
        if directory in visited:
            return
        visited.add(directory)
        kustomization_path = directory / KUSTOMIZATION_FILE
        if not kustomization_path.exists():
            return
        for pattern in ("*.yaml", "*.yml"):
            source_paths.update(
                path
                for path in directory.rglob(pattern)
                if path.name != KUSTOMIZATION_FILE
            )
        data = load_yaml_mapping(kustomization_path)
        for key in ("resources", "components"):
            for reference in data.get(key, []):
                if not isinstance(reference, str) or "://" in reference:
                    continue
                reference_path = (directory / reference).resolve()
                if reference_path.is_dir():
                    visit(reference_path)
                elif reference_path.suffix in {".yaml", ".yml"}:
                    source_paths.add(reference_path)

    visit(kustomization_dir)
    return sorted(source_paths)


def restore_source_comments(rendered: str, overlay_dir: Path) -> str:
    lines = rendered.splitlines()
    rendered_documents = [doc for doc in scan_yaml(rendered) if doc.doc_id is not None]
    documents_by_id = {doc.doc_id: doc for doc in rendered_documents}
    documents_by_gvk: dict[tuple[str, str], list[DocumentScan]] = {}
    for document in rendered_documents:
        assert document.doc_id is not None
        documents_by_gvk.setdefault(
            (document.doc_id.api_version, document.doc_id.kind), []
        ).append(document)

    def target_document(source_id: DocumentId) -> DocumentScan | None:
        if document := documents_by_id.get(source_id):
            return document
        candidates = documents_by_gvk.get((source_id.api_version, source_id.kind), [])
        return candidates[0] if len(candidates) == 1 else None

    insertions: dict[int, list[str]] = {}
    for source_path in source_comment_paths(overlay_dir):
        for document in scan_yaml(source_path.read_text(encoding="utf-8")):
            for block in document.comments:
                target = target_document(block.doc_id)
                line_number = target.targets.get(block.path) if target else None
                if line_number is None:
                    continue
                indent = " " * line_indent(lines[line_number])
                insertions.setdefault(line_number, []).extend(
                    f"{indent}{line}" for line in block.lines
                )
    restored: list[str] = []
    for line_number, line in enumerate(lines):
        restored.extend(insertions.get(line_number, []))
        restored.append(line)
    return "\n".join(restored) + "\n"


def reorder_rendered_top_level_fields(rendered: str) -> str:
    documents = [document.splitlines() for document in rendered.split("\n---\n")]
    reordered_documents: list[str] = []
    for document in documents:
        blocks: list[TopLevelBlock] = []
        current = TopLevelBlock(key=None, lines=[])
        for line in document:
            parsed = parse_key_value(line.strip()) if line_indent(line) == 0 else None
            key = parsed[0] if parsed and not line.lstrip().startswith("- ") else None
            if key is not None:
                if current.lines:
                    blocks.append(current)
                current = TopLevelBlock(key=key, lines=[line])
            else:
                current.lines.append(line)
        if current.lines:
            blocks.append(current)
        ordered = [
            block
            for key in FIRST_TOP_LEVEL_KEYS
            for block in blocks
            if block.key == key
        ]
        ordered.extend(
            block for block in blocks if block.key not in FIRST_TOP_LEVEL_KEYS
        )
        reordered_documents.append(
            "\n".join(line for block in ordered for line in block.lines).rstrip()
        )
    return "\n---\n".join(reordered_documents).rstrip() + "\n"


def rendered_header(config: MatrixConfig, overlay_dir: Path) -> str:
    return "\n".join(
        [
            "# Generated file. For repository contributors, do not edit this checked-in copy.",
            "# Regenerate every public overlay and rendered manifest of this matrix (from the repository root):",
            f"#   scripts/kustomize-matrix.py unfold {config.command_path}",
            f"{GENERATED_MANIFEST_PREFIX}{config.command_path}",
            "# Inspect only this Kustomize overlay (from the repository root):",
            f"#   kustomize build {display_path(overlay_dir)}",
            "# You may edit a copy before applying it.",
        ]
    )


def generated_manifest_paths(config: MatrixConfig) -> set[Path]:
    return {
        path
        for path in config.recipe_root.glob("deploy-*.yaml")
        if (
            GENERATED_MANIFEST_PREFIX in (content := path.read_text(encoding="utf-8"))
            or LEGACY_MATRIX_RENDER_COMMAND_PREFIX in content
            or LEGACY_GENERATED_MANIFEST_PREFIX in content
        )
    }


def is_current_generated_manifest(config: MatrixConfig, path: Path) -> bool:
    marker = f"{GENERATED_MANIFEST_PREFIX}{config.command_path}"
    return marker in path.read_text(encoding="utf-8")


def render_overlay(config: MatrixConfig, overlay_dir: Path) -> str:
    result = subprocess.run(
        [*kustomize_command(), str(overlay_dir)],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())
    rendered = reorder_rendered_top_level_fields(result.stdout)
    rendered = restore_source_comments(rendered, overlay_dir)
    return f"{SPDX_HEADER}\n\n{rendered_header(config, overlay_dir)}\n\n{rendered}"


def render_matrix(
    config: MatrixConfig, *, check: bool, clean: bool = False
) -> list[Path]:
    stale_overlays = unfold_matrix(config, check=True)
    if stale_overlays:
        if clean and not check:
            unfold_matrix(config, check=False, clean=True)
        else:
            raise RuntimeError(
                f"generated overlays are stale for {config.command_path}; run "
                f"scripts/kustomize-matrix.py unfold {config.command_path}"
            )
    generate_kustomize_openapi(check=check)

    variants = expand_matrix(config)
    expected_outputs = {
        config.recipe_root / f"deploy-{variant.name}.yaml" for variant in variants
    }
    stale: list[Path] = []
    for variant in variants:
        output_path = config.recipe_root / f"deploy-{variant.name}.yaml"
        rendered = render_overlay(config, overlay_path(config, variant))
        current = (
            output_path.read_text(encoding="utf-8") if output_path.exists() else None
        )
        if current != rendered:
            stale.append(output_path)
            if not check:
                output_path.write_text(rendered, encoding="utf-8")

    for output_path in generated_manifest_paths(config) - expected_outputs:
        stale.append(output_path)
        if not check and (clean or is_current_generated_manifest(config, output_path)):
            output_path.unlink()
    return stale


def generated_kustomization(target: Path, components: list[Path], root: Path) -> str:
    lines = [
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "sortOptions:",
        "  order: fifo",
        "resources:",
        f"  - {json.dumps(relative_path(target, root))}",
    ]
    if components:
        lines.append("components:")
        lines.extend(
            f"  - {json.dumps(relative_path(component, root))}"
            for component in components
        )
    return "\n".join(lines) + "\n"


def compose(target: str, components: list[str], build_options: list[str]) -> int:
    target_path = Path(target).resolve()
    if not target_path.is_dir():
        raise ValueError(f"Kustomize target is not a directory: {target}")
    component_paths = [Path(component).resolve() for component in components]
    missing_components = [
        component for component in component_paths if not component.is_dir()
    ]
    if missing_components:
        raise ValueError(
            f"Kustomize Component is not a directory: {missing_components[0]}"
        )
    common_path = Path(os.path.commonpath([target_path, *component_paths]))
    temporary_parent = target_path.parent if common_path == target_path else common_path
    with tempfile.TemporaryDirectory(
        prefix=".kustomize-matrix-", dir=temporary_parent
    ) as temporary_directory:
        temporary_root = Path(temporary_directory)
        (temporary_root / KUSTOMIZATION_FILE).write_text(
            generated_kustomization(target_path, component_paths, temporary_root),
            encoding="utf-8",
        )
        return subprocess.run(
            [*kustomize_command(), str(temporary_root), *build_options], check=False
        ).returncode


def matrix_paths(paths: list[str]) -> list[str]:
    if paths:
        return paths
    return [
        str(path)
        for path in sorted(REPO_ROOT.glob("recipes/**/.kustomize-matrix.yaml"))
    ]


def report_stale(kind: str, stale_paths: list[Path]) -> int:
    if not stale_paths:
        return 0
    print(f"Generated {kind} are stale:", file=sys.stderr)
    for path in sorted(set(stale_paths)):
        print(f"  {display_path(path)}", file=sys.stderr)
    return 1


def command_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("unfold", "render"):
        command_parser = subparsers.add_parser(command)
        mode = command_parser.add_mutually_exclusive_group()
        mode.add_argument("--check", action="store_true")
        mode.add_argument("--clean", action="store_true")
        command_parser.add_argument("matrices", nargs="+")
    check_parser = subparsers.add_parser("check")
    check_parser.add_argument("matrices", nargs="*")
    compose_parser = subparsers.add_parser("compose")
    compose_parser.add_argument("target")
    compose_parser.add_argument("arguments", nargs=argparse.REMAINDER)
    return parser


def main(arguments: list[str] | None = None) -> int:
    args = command_parser().parse_args(arguments)
    try:
        if args.command == "compose":
            component_end = 0
            while component_end < len(args.arguments) and not args.arguments[
                component_end
            ].startswith("-"):
                component_end += 1
            return compose(
                args.target,
                args.arguments[:component_end],
                args.arguments[component_end:],
            )

        configs = [load_matrix(path) for path in matrix_paths(args.matrices)]
        if not configs:
            raise ValueError("no .kustomize-matrix.yaml files found")
        if args.command == "unfold":
            stale_overlays = [
                path
                for config in configs
                for path in unfold_matrix(config, check=args.check, clean=args.clean)
            ]
            return (
                report_stale("Kustomize overlays", stale_overlays) if args.check else 0
            )
        if args.command == "render":
            stale_manifests = [
                path
                for config in configs
                for path in render_matrix(config, check=args.check, clean=args.clean)
            ]
            return (
                report_stale("recipe manifests", stale_manifests) if args.check else 0
            )

        stale_overlays = [
            path for config in configs for path in unfold_matrix(config, check=True)
        ]
        stale_manifests = (
            []
            if stale_overlays
            else [
                path for config in configs for path in render_matrix(config, check=True)
            ]
        )
        return report_stale("Kustomize overlays", stale_overlays) or report_stale(
            "recipe manifests", stale_manifests
        )
    except (OSError, RuntimeError, TypeError, ValueError) as exc:
        print(f"kustomize-matrix: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
