# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
source: kustomize/base
nameTemplate: "${variant}"
matrix:
  variant:
    - name: generic
      components: []
    - name: gke-rdma
      components:
        - kustomize/components/gke-rdma
