//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	batchv1 "k8s.io/api/batch/v1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api-inference-extension/apix/config/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompilationCacheConfig) DeepCopyInto(out *CompilationCacheConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompilationCacheConfig.
func (in *CompilationCacheConfig) DeepCopy() *CompilationCacheConfig {
	if in == nil {
		return nil
	}
	out := new(CompilationCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentCheckpointConfig) DeepCopyInto(out *ComponentCheckpointConfig) {
	*out = *in
	if in.CheckpointRef != nil {
		in, out := &in.CheckpointRef, &out.CheckpointRef
		*out = new(string)
		**out = **in
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(DynamoCheckpointIdentity)
		(*in).DeepCopyInto(*out)
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(ComponentCheckpointJobConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentCheckpointConfig.
func (in *ComponentCheckpointConfig) DeepCopy() *ComponentCheckpointConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentCheckpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentCheckpointJobConfig) DeepCopyInto(out *ComponentCheckpointJobConfig) {
	*out = *in
	if in.GMSClientContainers != nil {
		in, out := &in.GMSClientContainers, &out.GMSClientContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentCheckpointJobConfig.
func (in *ComponentCheckpointJobConfig) DeepCopy() *ComponentCheckpointJobConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentCheckpointJobConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentCheckpointStatus) DeepCopyInto(out *ComponentCheckpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentCheckpointStatus.
func (in *ComponentCheckpointStatus) DeepCopy() *ComponentCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReplicaStatus) DeepCopyInto(out *ComponentReplicaStatus) {
	*out = *in
	if in.ComponentNames != nil {
		in, out := &in.ComponentNames, &out.ComponentNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GPUsPerEngine != nil {
		in, out := &in.GPUsPerEngine, &out.GPUsPerEngine
		*out = new(int64)
		**out = **in
	}
	if in.GPUsPerReplica != nil {
		in, out := &in.GPUsPerReplica, &out.GPUsPerReplica
		*out = new(int64)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ScheduledReplicas != nil {
		in, out := &in.ScheduledReplicas, &out.ScheduledReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReplicaStatus.
func (in *ComponentReplicaStatus) DeepCopy() *ComponentReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentRoleSpec) DeepCopyInto(out *ComponentRoleSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = new(ProviderOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentRoleSpec.
func (in *ComponentRoleSpec) DeepCopy() *ComponentRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentInfoStatus) DeepCopyInto(out *DeploymentInfoStatus) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentInfoStatus.
func (in *DeploymentInfoStatus) DeepCopy() *DeploymentInfoStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoCheckpointIdentity) DeepCopyInto(out *DynamoCheckpointIdentity) {
	*out = *in
	if in.ExtraParameters != nil {
		in, out := &in.ExtraParameters, &out.ExtraParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoCheckpointIdentity.
func (in *DynamoCheckpointIdentity) DeepCopy() *DynamoCheckpointIdentity {
	if in == nil {
		return nil
	}
	out := new(DynamoCheckpointIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoComponentDeployment) DeepCopyInto(out *DynamoComponentDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoComponentDeployment.
func (in *DynamoComponentDeployment) DeepCopy() *DynamoComponentDeployment {
	if in == nil {
		return nil
	}
	out := new(DynamoComponentDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoComponentDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoComponentDeploymentList) DeepCopyInto(out *DynamoComponentDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoComponentDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoComponentDeploymentList.
func (in *DynamoComponentDeploymentList) DeepCopy() *DynamoComponentDeploymentList {
	if in == nil {
		return nil
	}
	out := new(DynamoComponentDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoComponentDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoComponentDeploymentSharedSpec) DeepCopyInto(out *DynamoComponentDeploymentSharedSpec) {
	*out = *in
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = new(ProviderOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.Multinode != nil {
		in, out := &in.Multinode, &out.Multinode
		*out = new(MultinodeSpec)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]ComponentRoleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedMemorySize != nil {
		in, out := &in.SharedMemorySize, &out.SharedMemorySize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ModelRef != nil {
		in, out := &in.ModelRef, &out.ModelRef
		*out = new(ModelReference)
		**out = **in
	}
	if in.ScalingAdapter != nil {
		in, out := &in.ScalingAdapter, &out.ScalingAdapter
		*out = new(ScalingAdapter)
		**out = **in
	}
	if in.EPPConfig != nil {
		in, out := &in.EPPConfig, &out.EPPConfig
		*out = new(EPPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FrontendSidecar != nil {
		in, out := &in.FrontendSidecar, &out.FrontendSidecar
		*out = new(string)
		**out = **in
	}
	if in.CompilationCache != nil {
		in, out := &in.CompilationCache, &out.CompilationCache
		*out = new(CompilationCacheConfig)
		**out = **in
	}
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(TopologyConstraint)
		**out = **in
	}
	if in.Experimental != nil {
		in, out := &in.Experimental, &out.Experimental
		*out = new(ExperimentalSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoComponentDeploymentSharedSpec.
func (in *DynamoComponentDeploymentSharedSpec) DeepCopy() *DynamoComponentDeploymentSharedSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoComponentDeploymentSharedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoComponentDeploymentSpec) DeepCopyInto(out *DynamoComponentDeploymentSpec) {
	*out = *in
	in.DynamoComponentDeploymentSharedSpec.DeepCopyInto(&out.DynamoComponentDeploymentSharedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoComponentDeploymentSpec.
func (in *DynamoComponentDeploymentSpec) DeepCopy() *DynamoComponentDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoComponentDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoComponentDeploymentStatus) DeepCopyInto(out *DynamoComponentDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(ComponentReplicaStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoComponentDeploymentStatus.
func (in *DynamoComponentDeploymentStatus) DeepCopy() *DynamoComponentDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DynamoComponentDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeployment) DeepCopyInto(out *DynamoGraphDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeployment.
func (in *DynamoGraphDeployment) DeepCopy() *DynamoGraphDeployment {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentComponentRef) DeepCopyInto(out *DynamoGraphDeploymentComponentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentComponentRef.
func (in *DynamoGraphDeploymentComponentRef) DeepCopy() *DynamoGraphDeploymentComponentRef {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentComponentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentExperimentalSpec) DeepCopyInto(out *DynamoGraphDeploymentExperimentalSpec) {
	*out = *in
	if in.KvTransferPolicy != nil {
		in, out := &in.KvTransferPolicy, &out.KvTransferPolicy
		*out = new(KvTransferPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentExperimentalSpec.
func (in *DynamoGraphDeploymentExperimentalSpec) DeepCopy() *DynamoGraphDeploymentExperimentalSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentExperimentalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentList) DeepCopyInto(out *DynamoGraphDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentList.
func (in *DynamoGraphDeploymentList) DeepCopy() *DynamoGraphDeploymentList {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentRequest) DeepCopyInto(out *DynamoGraphDeploymentRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentRequest.
func (in *DynamoGraphDeploymentRequest) DeepCopy() *DynamoGraphDeploymentRequest {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeploymentRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentRequestList) DeepCopyInto(out *DynamoGraphDeploymentRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeploymentRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentRequestList.
func (in *DynamoGraphDeploymentRequestList) DeepCopy() *DynamoGraphDeploymentRequestList {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeploymentRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentRequestSpec) DeepCopyInto(out *DynamoGraphDeploymentRequestSpec) {
	*out = *in
	if in.ModelCache != nil {
		in, out := &in.ModelCache, &out.ModelCache
		*out = new(ModelCacheSpec)
		**out = **in
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(HardwareSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SLA != nil {
		in, out := &in.SLA, &out.SLA
		*out = new(SLASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(OverridesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoApply != nil {
		in, out := &in.AutoApply, &out.AutoApply
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentRequestSpec.
func (in *DynamoGraphDeploymentRequestSpec) DeepCopy() *DynamoGraphDeploymentRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentRequestStatus) DeepCopyInto(out *DynamoGraphDeploymentRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProfilingResults != nil {
		in, out := &in.ProfilingResults, &out.ProfilingResults
		*out = new(ProfilingResultsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentInfo != nil {
		in, out := &in.DeploymentInfo, &out.DeploymentInfo
		*out = new(DeploymentInfoStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentRequestStatus.
func (in *DynamoGraphDeploymentRequestStatus) DeepCopy() *DynamoGraphDeploymentRequestStatus {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentScalingAdapter) DeepCopyInto(out *DynamoGraphDeploymentScalingAdapter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentScalingAdapter.
func (in *DynamoGraphDeploymentScalingAdapter) DeepCopy() *DynamoGraphDeploymentScalingAdapter {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentScalingAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeploymentScalingAdapter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentScalingAdapterList) DeepCopyInto(out *DynamoGraphDeploymentScalingAdapterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoGraphDeploymentScalingAdapter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentScalingAdapterList.
func (in *DynamoGraphDeploymentScalingAdapterList) DeepCopy() *DynamoGraphDeploymentScalingAdapterList {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentScalingAdapterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoGraphDeploymentScalingAdapterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentScalingAdapterSpec) DeepCopyInto(out *DynamoGraphDeploymentScalingAdapterSpec) {
	*out = *in
	out.DGDRef = in.DGDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentScalingAdapterSpec.
func (in *DynamoGraphDeploymentScalingAdapterSpec) DeepCopy() *DynamoGraphDeploymentScalingAdapterSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentScalingAdapterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentScalingAdapterStatus) DeepCopyInto(out *DynamoGraphDeploymentScalingAdapterStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentScalingAdapterStatus.
func (in *DynamoGraphDeploymentScalingAdapterStatus) DeepCopy() *DynamoGraphDeploymentScalingAdapterStatus {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentScalingAdapterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentSpec) DeepCopyInto(out *DynamoGraphDeploymentSpec) {
	*out = *in
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = new(ProviderOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]DynamoComponentDeploymentSharedSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Restart != nil {
		in, out := &in.Restart, &out.Restart
		*out = new(Restart)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(SpecTopologyConstraint)
		**out = **in
	}
	if in.Experimental != nil {
		in, out := &in.Experimental, &out.Experimental
		*out = new(DynamoGraphDeploymentExperimentalSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentSpec.
func (in *DynamoGraphDeploymentSpec) DeepCopy() *DynamoGraphDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoGraphDeploymentStatus) DeepCopyInto(out *DynamoGraphDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(map[string]ComponentReplicaStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Restart != nil {
		in, out := &in.Restart, &out.Restart
		*out = new(RestartStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make(map[string]ComponentCheckpointStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoGraphDeploymentStatus.
func (in *DynamoGraphDeploymentStatus) DeepCopy() *DynamoGraphDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DynamoGraphDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EPPConfig) DeepCopyInto(out *EPPConfig) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1alpha1.EndpointPickerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EPPConfig.
func (in *EPPConfig) DeepCopy() *EPPConfig {
	if in == nil {
		return nil
	}
	out := new(EPPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExperimentalSpec) DeepCopyInto(out *ExperimentalSpec) {
	*out = *in
	if in.GPUMemoryService != nil {
		in, out := &in.GPUMemoryService, &out.GPUMemoryService
		*out = new(GPUMemoryServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = new(FailoverSpec)
		**out = **in
	}
	if in.Grove != nil {
		in, out := &in.Grove, &out.Grove
		*out = new(GroveSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = new(ComponentCheckpointConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExperimentalSpec.
func (in *ExperimentalSpec) DeepCopy() *ExperimentalSpec {
	if in == nil {
		return nil
	}
	out := new(ExperimentalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverSpec.
func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesSpec) DeepCopyInto(out *FeaturesSpec) {
	*out = *in
	if in.Planner != nil {
		in, out := &in.Planner, &out.Planner
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.KVRouter != nil {
		in, out := &in.KVRouter, &out.KVRouter
		*out = new(KVRouterSpec)
		**out = **in
	}
	if in.Mocker != nil {
		in, out := &in.Mocker, &out.Mocker
		*out = new(MockerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesSpec.
func (in *FeaturesSpec) DeepCopy() *FeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GMSClientPodSpec) DeepCopyInto(out *GMSClientPodSpec) {
	*out = *in
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GMSClientPodSpec.
func (in *GMSClientPodSpec) DeepCopy() *GMSClientPodSpec {
	if in == nil {
		return nil
	}
	out := new(GMSClientPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMemoryServiceSpec) DeepCopyInto(out *GPUMemoryServiceSpec) {
	*out = *in
	if in.ExtraClientContainers != nil {
		in, out := &in.ExtraClientContainers, &out.ExtraClientContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraClientPods != nil {
		in, out := &in.ExtraClientPods, &out.ExtraClientPods
		*out = make([]GMSClientPodSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMemoryServiceSpec.
func (in *GPUMemoryServiceSpec) DeepCopy() *GPUMemoryServiceSpec {
	if in == nil {
		return nil
	}
	out := new(GPUMemoryServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroveSpec) DeepCopyInto(out *GroveSpec) {
	*out = *in
	if in.ForceScalingGroup != nil {
		in, out := &in.ForceScalingGroup, &out.ForceScalingGroup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroveSpec.
func (in *GroveSpec) DeepCopy() *GroveSpec {
	if in == nil {
		return nil
	}
	out := new(GroveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareSpec) DeepCopyInto(out *HardwareSpec) {
	*out = *in
	if in.VRAMMB != nil {
		in, out := &in.VRAMMB, &out.VRAMMB
		*out = new(float64)
		**out = **in
	}
	if in.TotalGPUs != nil {
		in, out := &in.TotalGPUs, &out.TotalGPUs
		*out = new(int32)
		**out = **in
	}
	if in.NumGPUsPerNode != nil {
		in, out := &in.NumGPUsPerNode, &out.NumGPUsPerNode
		*out = new(int32)
		**out = **in
	}
	if in.RDMA != nil {
		in, out := &in.RDMA, &out.RDMA
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareSpec.
func (in *HardwareSpec) DeepCopy() *HardwareSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVRouterSpec) DeepCopyInto(out *KVRouterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVRouterSpec.
func (in *KVRouterSpec) DeepCopy() *KVRouterSpec {
	if in == nil {
		return nil
	}
	out := new(KVRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KvTransferPolicy) DeepCopyInto(out *KvTransferPolicy) {
	*out = *in
	if in.PreferredWeight != nil {
		in, out := &in.PreferredWeight, &out.PreferredWeight
		*out = new(float32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KvTransferPolicy.
func (in *KvTransferPolicy) DeepCopy() *KvTransferPolicy {
	if in == nil {
		return nil
	}
	out := new(KvTransferPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockerSpec) DeepCopyInto(out *MockerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockerSpec.
func (in *MockerSpec) DeepCopy() *MockerSpec {
	if in == nil {
		return nil
	}
	out := new(MockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheSpec) DeepCopyInto(out *ModelCacheSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheSpec.
func (in *ModelCacheSpec) DeepCopy() *ModelCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReference) DeepCopyInto(out *ModelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReference.
func (in *ModelReference) DeepCopy() *ModelReference {
	if in == nil {
		return nil
	}
	out := new(ModelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultinodeSpec) DeepCopyInto(out *MultinodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultinodeSpec.
func (in *MultinodeSpec) DeepCopy() *MultinodeSpec {
	if in == nil {
		return nil
	}
	out := new(MultinodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverridesSpec) DeepCopyInto(out *OverridesSpec) {
	*out = *in
	if in.ProfilingJob != nil {
		in, out := &in.ProfilingJob, &out.ProfilingJob
		*out = new(batchv1.JobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DGD != nil {
		in, out := &in.DGD, &out.DGD
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverridesSpec.
func (in *OverridesSpec) DeepCopy() *OverridesSpec {
	if in == nil {
		return nil
	}
	out := new(OverridesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParetoConfig) DeepCopyInto(out *ParetoConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParetoConfig.
func (in *ParetoConfig) DeepCopy() *ParetoConfig {
	if in == nil {
		return nil
	}
	out := new(ParetoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementStatus) DeepCopyInto(out *PlacementStatus) {
	*out = *in
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementStatus.
func (in *PlacementStatus) DeepCopy() *PlacementStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingResultsStatus) DeepCopyInto(out *ProfilingResultsStatus) {
	*out = *in
	if in.Pareto != nil {
		in, out := &in.Pareto, &out.Pareto
		*out = make([]ParetoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectedConfig != nil {
		in, out := &in.SelectedConfig, &out.SelectedConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingResultsStatus.
func (in *ProfilingResultsStatus) DeepCopy() *ProfilingResultsStatus {
	if in == nil {
		return nil
	}
	out := new(ProfilingResultsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderOverride) DeepCopyInto(out *ProviderOverride) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderOverride.
func (in *ProviderOverride) DeepCopy() *ProviderOverride {
	if in == nil {
		return nil
	}
	out := new(ProviderOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Restart) DeepCopyInto(out *Restart) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(RestartStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Restart.
func (in *Restart) DeepCopy() *Restart {
	if in == nil {
		return nil
	}
	out := new(Restart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartStatus) DeepCopyInto(out *RestartStatus) {
	*out = *in
	if in.InProgress != nil {
		in, out := &in.InProgress, &out.InProgress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartStatus.
func (in *RestartStatus) DeepCopy() *RestartStatus {
	if in == nil {
		return nil
	}
	out := new(RestartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartStrategy) DeepCopyInto(out *RestartStrategy) {
	*out = *in
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartStrategy.
func (in *RestartStrategy) DeepCopy() *RestartStrategy {
	if in == nil {
		return nil
	}
	out := new(RestartStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateStatus) DeepCopyInto(out *RollingUpdateStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.UpdatedComponents != nil {
		in, out := &in.UpdatedComponents, &out.UpdatedComponents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateStatus.
func (in *RollingUpdateStatus) DeepCopy() *RollingUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLASpec) DeepCopyInto(out *SLASpec) {
	*out = *in
	if in.TTFT != nil {
		in, out := &in.TTFT, &out.TTFT
		*out = new(float64)
		**out = **in
	}
	if in.ITL != nil {
		in, out := &in.ITL, &out.ITL
		*out = new(float64)
		**out = **in
	}
	if in.E2ELatency != nil {
		in, out := &in.E2ELatency, &out.E2ELatency
		*out = new(float64)
		**out = **in
	}
	if in.OptimizationType != nil {
		in, out := &in.OptimizationType, &out.OptimizationType
		*out = new(OptimizationType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLASpec.
func (in *SLASpec) DeepCopy() *SLASpec {
	if in == nil {
		return nil
	}
	out := new(SLASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdapter) DeepCopyInto(out *ScalingAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdapter.
func (in *ScalingAdapter) DeepCopy() *ScalingAdapter {
	if in == nil {
		return nil
	}
	out := new(ScalingAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecTopologyConstraint) DeepCopyInto(out *SpecTopologyConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecTopologyConstraint.
func (in *SpecTopologyConstraint) DeepCopy() *SpecTopologyConstraint {
	if in == nil {
		return nil
	}
	out := new(SpecTopologyConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConstraint) DeepCopyInto(out *TopologyConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConstraint.
func (in *TopologyConstraint) DeepCopy() *TopologyConstraint {
	if in == nil {
		return nil
	}
	out := new(TopologyConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.ISL != nil {
		in, out := &in.ISL, &out.ISL
		*out = new(int32)
		**out = **in
	}
	if in.OSL != nil {
		in, out := &in.OSL, &out.OSL
		*out = new(int32)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(float64)
		**out = **in
	}
	if in.RequestRate != nil {
		in, out := &in.RequestRate, &out.RequestRate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
